### ISSUE TITLE
undefined method ``

### ISSUE THREAD

**Issue by chrisrock1010** [sparkleformation/sparkle_formation#165]
Hi, 
my component looks like this and i would like to execute system command but i got 

Code: 
```
require 'json'

amis = {}
amis['ubuntu'] = {}
regions = %w{us-east-1 us-west-1 us-west-2 eu-west-1 eu-central-1 sa-east-1 ap-southeast-1 ap-southeast-2 ap-northeast-1}

regions.each do |region|
  ami_json = `aws ec2 describe-images --owners self --query 'Images[?starts_with(Name, \`asy-ubuntu-1404-chef-sensu\`) == \`true\`].{Name:Name,ID:ImageId}' --profile asy_prod --region #{region}`

  images = JSON.parse(ami_json).sort_by { |hash| hash['Name'] }
  latest_image = images.last

  next if latest_image.nil?

  amis['ubuntu'][region] = {} if amis['ubuntu'][region].nil?
  amis['ubuntu'][region]["UbuntuSsd"] = latest_image["ID"]
  amis['ubuntu'][region]["UbuntuIo"] = latest_image["ID"]
end


SparkleFormation.build do

  regions.each do |region|
    mappings.platforms.set!(region._no_hump, amis['ubuntu'][region])
  end

end
```
Error:
```
/home/user/ubuntu_asy.rb:8:in `block (3 levels) in load_parts!': undefined method ``' for #<#<Class:0x000000022cbc88>:0x000000022b10b8> (NoMethodError)
	from /home/user/REPO/chef/cloud/cloud-sparkle-formation/cloudformation/components/ubuntu_asy.rb:7:in `each'
	from /home/user/REPO/chef/cloud/cloud-sparkle-formation/cloudformation/components/ubuntu_asy.rb:7:in `block (2 levels) in load_parts!'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle.rb:317:in `instance_eval'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle.rb:317:in `block (2 levels) in load_parts!'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle.rb:313:in `each'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle.rb:313:in `block in load_parts!'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/bogo-0.2.4/lib/bogo/memoization.rb:64:in `memoize'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle.rb:312:in `load_parts!'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle.rb:227:in `initialize'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:398:in `new'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:398:in `initialize'
	from templates/base.rb:1:in `new'
	from templates/base.rb:1:in `compile'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:103:in `instance_eval'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-2.1.8/lib/sparkle_formation/sparkle_formation.rb:103:in `compile'
	from asy.rb:18:in `block in <main>'
	from asy.rb:14:in `each'
	from asy.rb:14:in `<main>'
```

Thanks for your help

**Comment by jimcroft** [comment]
No idea why backticks don't work but I'd suggest using IO::popen instead (http://ruby-doc.org/core-2.3.0/IO.html#method-c-popen) or, much better, the Ruby aws-sdk directly.

There's a simple example (as a registry rather than a component but idea's the same) here https://github.com/hw-labs/sparkle-pack-aws-availability-zones/blob/master/lib/sparkleformation/registry/get_azs.rb

**Comment by chrisroberts** [comment]
Hi! +1 on @jimcroft's suggestion to use the aws-sdk rather than shelling out. For shelling out though, you can use the `system!` helper: http://www.sparkleformation.io/docs/sparkle_formation/helper-methods.html#local-system-call

Cheers!

**Comment by chrisroberts** [comment]
And to add on a little more, the code block you have to build the ami hash would be better suited within a registry item that returns the hash result. Then you can request it via the `registry!` helper. This prevents the code from being run every time SparkleFormation loads and only runs it when required (when the component is actually in use).
