### ISSUE TITLE
User without UpdateStack credentials gets erronious error on update

### ISSUE THREAD

**Issue by grahamc** [sparkleformation/sparkle_formation#185]
```
$ DEBUG=true sfn update private-space-v6
I, [2016-07-01T12:58:10.150261 #13835]  INFO -- : Lock aquired for stack update. Requesting stacks from upstream. (#<Thread:0x000000012071e0>)
I, [2016-07-01T12:58:10.393428 #13835]  INFO -- : Stack list has been updated from upstream and cached locally
[Sfn]: SparkleFormation: update
[Sfn]:   -> Name: private-v6 (no template update)
ERROR: NoMethodError: undefined method `[]' for nil:NilClass
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/sfn-3.0.18/lib/sfn/command_module/stack.rb:117:in `block in prefix_parameters_setup'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/sfn-3.0.18/lib/sfn/command_module/stack.rb:116:in `map'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/sfn-3.0.18/lib/sfn/command_module/stack.rb:116:in `prefix_parameters_setup'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/sfn-3.0.18/lib/sfn/command_module/stack.rb:218:in `populate_parameters!'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/sfn-3.0.18/lib/sfn/command/update.rb:114:in `execute!'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/sfn-3.0.18/bin/sfn:52:in `block (4 levels) in <top (required)>'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/bogo-cli-0.2.8/lib/bogo-cli/setup.rb:26:in `call'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/bogo-cli-0.2.8/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/slop-3.6.0/lib/slop.rb:260:in `call'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/bogo-cli-0.2.8/lib/bogo-cli/setup.rb:48:in `define'
/nix/store/ppq1yzmp2ishvrs62pxh3sl63xk09y81-sfn-2.1.10/lib/ruby/gems/2.2.3/gems/sfn-3.0.18/bin/sfn:14:in `<top (required)>'
/nix/store/2z9wb3l3djwy0ci8ffmpx3k6zilwqf8z-sfn/bin/sfn:18:in `load'
/nix/store/2z9wb3l3djwy0ci8ffmpx3k6zilwqf8z-sfn/bin/sfn:18:in `<main>'

```

**Comment by chrisroberts** [comment]
Lets do some better error checking to properly surface root cause (like lack of permissions). This is going to be a sfn thing though, so I'll create an issue over there.
