### ISSUE TITLE
RuntimeError: entity expansion has grown too large

### ISSUE THREAD

**Issue by jimcroft** [sparkleformation/sparkle_formation#189]
We've got a very large template that until recently was working ok using the `--upload-root-template` flag. We've just started getting the following error on stack updates:

`ERROR: RuntimeError: entity expansion has grown too large`

The template is 140951 bytes on disk, well within the 460800 byte limit on S3 loaded templates.

Any ideas what's going on?

Stack trace is as follows:

```
ERROR: RuntimeError: entity expansion has grown too large
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/text.rb:398:in `block in unnormalize'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/text.rb:395:in `gsub'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/text.rb:395:in `unnormalize'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/text.rb:252:in `value'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/element.rb:452:in `text'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/element.rb:433:in `has_text?'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:57:in `merge_texts!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:46:in `collapse'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:31:in `merge_element!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:42:in `block in collapse'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/element.rb:902:in `block in each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/xpath.rb:67:in `each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/xpath.rb:67:in `each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/element.rb:902:in `each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/element.rb:393:in `each_element'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:42:in `collapse'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:31:in `merge_element!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:42:in `block in collapse'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/element.rb:902:in `block in each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/xpath.rb:67:in `each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/xpath.rb:67:in `each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/element.rb:902:in `each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/2.2.0/rexml/element.rb:393:in `each_element'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:42:in `collapse'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:31:in `merge_element!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_xml-0.5.5/lib/multi_xml/parsers/rexml.rb:16:in `parse'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/multi_xml-0.5.5/lib/multi_xml.rb:138:in `parse'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/miasma-0.3.2/lib/miasma/types/api.rb:237:in `from_xml'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/miasma-0.3.2/lib/miasma/types/api.rb:197:in `format_response'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/miasma-0.3.2/lib/miasma/types/api.rb:130:in `request'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/miasma-aws-0.3.4/lib/miasma/contrib/aws/orchestration.rb:252:in `stack_template_load'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/miasma-0.3.2/lib/miasma/models/orchestration/stack.rb:141:in `block in perform_template_load'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-0.2.4/lib/bogo/memoization.rb:64:in `memoize'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/miasma-0.3.2/lib/miasma/models/orchestration/stack.rb:140:in `perform_template_load'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-0.2.4/lib/bogo/lazy.rb:135:in `block in attribute'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sfn-3.0.18/lib/sfn/command/update.rb:79:in `execute!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sfn-3.0.18/bin/sfn:52:in `block (4 levels) in <top (required)>'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-cli-0.2.8/lib/bogo-cli/setup.rb:26:in `call'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-cli-0.2.8/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/bogo-cli-0.2.8/lib/bogo-cli/setup.rb:48:in `define'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sfn-3.0.18/bin/sfn:14:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/sfn:23:in `load'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bin/sfn:23:in `<main>'
```

**Comment by jimcroft** [comment]
FWIW running with the `--print-only` flag succeeds without error.
