### ISSUE TITLE
Dynamic as function?

### ISSUE THREAD

**Issue by zeldigas** [sparkleformation/sparkle_formation#207]
Hello

I want to create dynamic with return value. Use case is simple - define reusable piece of code to generate unified project/company wide names for resources by template.

Here what I tried to do:
1. defined dynamic
```
SparkleFormation.dynamic(:my_resource) do |_name, _config={}|
    part_organization_name = 'org'
    region_short_name = 'usw2'
    resource_name = join!(part_organization_name,
                          _config[:app],
                          region_short_name,
                          _config[:env],
                          _name,
                          {
                              options: {
                                  delimiter: '-'
                              }
                          })
    resource_name
end
```
2. Use it somewhere in template, say in creating dynamodb with proper name
```
full_table_name = dynamic!(:my_resource, 'test-table', {:app => 'hello', :env => 'staging'})

dynamic!(:dynamodb_table, t_name) do

      properties do
        table_name full_table_name
        #other properties
      end
end
```

But now I get strange stack trace error (sparkle is executed via stack_master):
```
stack_master diff -c conf.yml us-west-2 a_stack
Executing diff on a_stack in us-west-2
/usr/local/bundle/gems/attribute_struct-0.3.4/lib/attribute_struct/attribute_struct.rb:351:in `respond_to?': stack level too deep (SystemStackError)
        from /usr/local/bundle/gems/attribute_struct-0.3.4/lib/attribute_struct/attribute_struct.rb:351:in `_dump_unpacker'
        from /usr/local/bundle/gems/attribute_struct-0.3.4/lib/attribute_struct/attribute_struct.rb:375:in `block in _dump'
        from /usr/local/bundle/gems/attribute_struct-0.3.4/lib/attribute_struct/attribute_struct.rb:373:in `map'
        from /usr/local/bundle/gems/attribute_struct-0.3.4/lib/attribute_struct/attribute_struct.rb:373:in `_dump'
        from /usr/local/bundle/gems/attribute_struct-0.3.4/lib/attribute_struct/attribute_struct.rb:365:in `_dump_unpacker'
        from /usr/local/bundle/gems/attribute_struct-0.3.4/lib/attribute_struct/attribute_struct.rb:375:in `block in _dump'
        from /usr/local/bundle/gems/attribute_struct-0.3.4/lib/attribute_struct/attribute_struct.rb:373:in `map'
        from /usr/local/bundle/gems/attribute_struct-0.3.4/lib/attribute_struct/attribute_struct.rb:373:in `_dump'
         ... 9345 levels...
        from /usr/local/bundle/gems/stack_master-0.12.0/lib/stack_master/cli.rb:172:in `execute!'
        from /usr/local/bundle/gems/stack_master-0.12.0/bin/stack_master:13:in `<top (required)>'
        from /usr/local/bundle/bin/stack_master:22:in `load'
        from /usr/local/bundle/bin/stack_master:22:in `<main>'
```

Could you please advise if it possible and if it possible, what am I doing wrong?

**Comment by chrisroberts** [comment]
Hi! The `dynamic!`s are used for injecting structure into the document. Here, you are wanting only to compute a name, not inject structure. A registry item would be better suited for this functionality:

```ruby
SparkleFormation.register!(:resource_namer) do |_name, _config={}|
    part_organization_name = 'org'
    region_short_name = 'usw2'
    resource_name = join!(part_organization_name,
                          _config[:app],
                          region_short_name,
                          _config[:env],
                          _name,
                          {
                              options: {
                                  delimiter: '-'
                              }
                          })
    resource_name
end
```

which you can then use as:

```ruby
dynamic!(:dynamodb_table, t_name) do
  properties do
    table_name registry!(:resource_namer, 'test-table', {:app => 'hello', :env => 'staging'})
    #other properties
  end
end
```

Cheers!

**Comment by zeldigas** [comment]
@chrisroberts thank you for prompt response!
