### ISSUE TITLE
ERROR: NoMethodError: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by jamesla** [sparkleformation/sparkle_formation#224]
My stack keeps getting itself into a state where I get the following error message after an `sfn update`. Destroying and recreating it fixes it. Once the stack is in this state I can actually keep updating it etc but the exception will be thrown each time causing the event stream to  #disconnect.

I noticed that same others have reported the same error which has been resolved. Any ideas on how to stop this from happening? 

```
[I] 15:04:42 ➜  sparkleformation git:(sparkle-test) ✗
sfn update plus --file plus --apply-stack mgmt --defaults --debug
I, [2017-06-30T15:05:53.139646 #12014]  INFO -- : Lock aquired for stack update. Requesting stacks from upstream. (#<Thread:0x0056042db4a1b8>)
I, [2017-06-30T15:05:54.005809 #12014]  INFO -- : Stack list has been updated from upstream and cached locally
[DEBUG]: Compile parameters - {}
[DEBUG]: Initial compile parameters - {}
[DEBUG]: Merged compile parameters - {}
[Sfn]: SparkleFormation: update
I, [2017-06-30T15:05:56.342125 #12014]  INFO -- : Lock aquired for stack update. Requesting stacks from upstream. (#<Thread:0x0056042db4a1b8>)
I, [2017-06-30T15:05:56.343085 #12014]  INFO -- : Stack list has been updated from upstream and cached locally
[Sfn]: Stack runtime parameters: - template: plus
[Sfn]: Pre-update resource planning report:

  Update plan for: plus
    Resources to be added:
      [AWS::ElasticLoadBalancingV2::Listener]    TestPlusAlbHttpElasticloadbalancingv2Listener

[Sfn]: Apply this stack update? (Y/N): y
[Sfn]: Events for Stack: plus
I, [2017-06-30T15:06:02.069200 #12014]  INFO -- : Lock aquired for stack update. Requesting stacks from upstream. (#<Thread:0x0056042db4a1b8>)
I, [2017-06-30T15:06:02.544149 #12014]  INFO -- : Stack list has been updated from upstream and cached locally
Time                      Resource Logical Id   Resource Status      Resource Status Reason
2017-06-30 05:06:01 UTC   plus                  UPDATE_IN_PROGRESS   User Initiated
ERROR: NoMethodError: undefined method `map' for nil:NilClass
Did you mean?  tap
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:80:in `block in get_events'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:65:in `map'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:65:in `get_events'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:35:in `method_missing'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:24:in `block (3 levels) in execute!'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:56:in `table'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:23:in `block (2 levels) in execute!'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:78:in `instance_exec'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:78:in `display'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:49:in `block in execute!'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command_module/callbacks.rb:19:in `api_action!'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command/events.rb:21:in `execute!'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command_module/base.rb:129:in `poll_stack'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command/update.rb:146:in `block in execute!'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command_module/callbacks.rb:19:in `api_action!'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/lib/sfn/command/update.rb:143:in `execute!'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/bin/sfn:52:in `block (4 levels) in <top (required)>'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:48:in `define'
/home/vagrant/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sfn-3.0.26/bin/sfn:14:in `<top (required)>'
/home/vagrant/.rbenv/versions/2.3.4/bin/sfn:22:in `load'
/home/vagrant/.rbenv/versions/2.3.4/bin/sfn:22:in `<main>'
```

**Comment by jamesla** [comment]
Just closed?
