### ISSUE TITLE
[ERROR]: Unexpected error when generating plan information: NoMethodError - undefined method `to_sym' for ["interrupt", "none"]:Array

### ISSUE THREAD

**Issue by gramosbr** [sparkleformation/sparkle_formation#264]
Updating a nested stack parameters cause 
```
[ERROR]: Unexpected error when generating plan information: NoMethodError - undefined method `to_sym' for ["interrupt", "none"]:Array
``` 

Stack trace:
```
[DEBUG]: NoMethodError: undefined method `to_sym' for ["interrupt", "none"]:Array
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/sfn-3.1.8/lib/sfn/planner/aws.rb:588:in `register_diff'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/sfn-3.1.8/lib/sfn/planner/aws.rb:447:in `block in run_stack_diff'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/sfn-3.1.8/lib/sfn/planner/aws.rb:446:in `each'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/sfn-3.1.8/lib/sfn/planner/aws.rb:446:in `run_stack_diff'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/sfn-3.1.8/lib/sfn/planner/aws.rb:374:in `plan_stack'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/sfn-3.1.8/lib/sfn/planner/aws.rb:252:in `generate_plan'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/sfn-3.1.8/lib/sfn/command/update.rb:98:in `execute!'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/sfn-3.1.8/bin/sfn:52:in `block (4 levels) in <top (required)>'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bogo-cli-0.2.18/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bogo-cli-0.2.18/lib/bogo-cli/setup.rb:50:in `define'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/sfn-3.1.8/bin/sfn:14:in `<top (required)>'
/Users/gramos/.rbenv/versions/2.4.6/bin/sfn:23:in `load'
/Users/gramos/.rbenv/versions/2.4.6/bin/sfn:23:in `<top (required)>'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/gramos/.rbenv/versions/2.4.6/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
/Users/gramos/.rbenv/versions/2.4.6/bin/bundle:23:in `load'
/Users/gramos/.rbenv/versions/2.4.6/bin/bundle:23:in `<main>' 
```

Issue was introduced on revision 5b62aa439ae38f830add44645af16324f0c48f6d,
by 
```
...
- "update_causes": "interrupt"
...
+ "update_causes": [
+           "interrupt",
+           "none"
+ ]

```

And that is not handled by `/lib/sparkle_formation/resources.rb` where 
`if conditionals && final_resource` is always evaluated to false that returns the default `self[:update_causes]`

**Comment by chrisroberts** [comment]
Fixed on main with generated resource list only providing single value for `update_causes`. Thanks for the report and apologies for the delay. Cheers!
