### ISSUE TITLE
Miasma::Error - Failed to load requested API type :Orchestration (Reason: NoMethodError - undefined method `synchronize' for nil:NilClass)

### ISSUE THREAD

**Issue by Johannes1509** [sparkleformation/sparkle_formation#274]
I'm following the Getting started Guide from the official SparkleFormation website and just encountered the following error while running the `bundle exec sfn list` command. What can I do?

```
jd@LAPTOP-0:~/sparkle-guide$ sudo bundle exec sfn list --debug
D, [2022-09-09T11:26:12.050591 #350] DEBUG -- miasma.aws.orchestration: running custom setup configuration updates
[ERROR]: Failed to create remote API connection. Please validate configuration!
[ERROR]: Connection failure reason - Miasma::Error - Failed to load requested API type :Orchestration (Reason: NoMethodError - undefined method `synchronize' for nil:NilClass)
[ERROR]: Failed to load requested API type :Orchestration (Reason: NoMethodError - undefined method `synchronize' for nil:NilClass)
[DEBUG]: Stacktrace: Miasma::Error: Failed to load requested API type :Orchestration (Reason: NoMethodError - undefined method `synchronize' for nil:NilClass)
/var/lib/gems/3.0.0/gems/miasma-0.3.8/lib/miasma.rb:51:in `rescue in api'
/var/lib/gems/3.0.0/gems/miasma-0.3.8/lib/miasma.rb:38:in `api'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/lib/sfn/provider.rb:73:in `initialize'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/lib/sfn/command_module/base.rb:37:in `new'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/lib/sfn/command_module/base.rb:37:in `block in provider_for'
/var/lib/gems/3.0.0/gems/bogo-0.2.15/lib/bogo/memoization.rb:59:in `memoize'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/lib/sfn/command_module/base.rb:36:in `provider_for'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/lib/sfn/command/list.rb:36:in `get_stacks'
/var/lib/gems/3.0.0/gems/bogo-ui-0.1.28/lib/bogo-ui/table.rb:35:in `method_missing'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/lib/sfn/command/list.rb:13:in `block (3 levels) in execute!'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/lib/sfn/command_module/callbacks.rb:20:in `api_action!'
/var/lib/gems/3.0.0/gems/bogo-ui-0.1.28/lib/bogo-ui/table.rb:35:in `method_missing'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/lib/sfn/command/list.rb:13:in `block (2 levels) in execute!'
/var/lib/gems/3.0.0/gems/bogo-ui-0.1.28/lib/bogo-ui/table.rb:56:in `table'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/lib/sfn/command/list.rb:12:in `block in execute!'
/var/lib/gems/3.0.0/gems/bogo-ui-0.1.28/lib/bogo-ui/table.rb:78:in `instance_exec'
/var/lib/gems/3.0.0/gems/bogo-ui-0.1.28/lib/bogo-ui/table.rb:78:in `display'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/lib/sfn/command/list.rb:29:in `execute!'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/bin/sfn:52:in `block (4 levels) in <top (required)>'
/var/lib/gems/3.0.0/gems/bogo-cli-0.2.18/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/var/lib/gems/3.0.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/var/lib/gems/3.0.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/var/lib/gems/3.0.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/var/lib/gems/3.0.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/var/lib/gems/3.0.0/gems/bogo-cli-0.2.18/lib/bogo-cli/setup.rb:50:in `define'
/var/lib/gems/3.0.0/gems/sfn-3.1.8/bin/sfn:14:in `<top (required)>'
/usr/local/bin/sfn:25:in `load'
/usr/local/bin/sfn:25:in `<top (required)>'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `load'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:58:in `kernel_load'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/lib/bundler/cli/exec.rb:23:in `run'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/lib/bundler/cli.rb:486:in `exec'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/lib/bundler/cli.rb:31:in `dispatch'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/lib/bundler/cli.rb:25:in `start'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/exe/bundle:48:in `block in <top (required)>'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/var/lib/gems/3.0.0/gems/bundler-2.3.22/exe/bundle:36:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
```

Additional informations:
```
jd@LAPTOP-0:~/sparkle-guide$ sudo bundle update
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using hashie 5.0.0
Using public_suffix 5.0.0
Using multi_json 1.15.0
Using multi_xml 0.6.0
Using colored 1.2
Using paint 2.3.0
Using bundler 2.3.22
Using unf_ext 0.0.8.2
Using graph 2.8.2
Using hashdiff 0.2.3
Using http-form_data 2.3.0
Using http_parser.rb 0.6.0
Using jmespath 1.6.1
Using rexml 3.2.5
Using miasma-azure 0.1.4
Using mime-types-data 3.2022.0105
Using miasma-open-stack 0.1.4
Using miasma-terraform 0.1.2
Using net-ssh 7.0.1
Using addressable 2.8.1
Using bogo 0.2.15
Using slop 3.6.0
Using attribute_struct 0.4.4
Using unf 0.1.4
Using xml-simple 1.1.9
Using mime-types 3.4.1
Using miasma-rackspace 0.1.2
Using command_line_reporter 4.0.2
Using domain_name 0.5.20190701
Using sparkle_formation 3.0.40
Using bogo-config 0.3.0
Using bogo-ui 0.1.28
Using http-cookie 1.0.5
Using bogo-cli 0.2.18
Using http 3.3.0
Using miasma 0.3.8
Using miasma-aws 0.3.30
Using miasma-google 0.1.0
Using sfn 3.1.8
```

````
jd@LAPTOP-0:~/sparkle-guide$ bundle exec sfn conf
[Sfn]: Current configuration state:
  apply_nesting: deep
  colors: true
  credentials:
    aws_profile_name: test
    provider: aws
  file_path_prompt: true
  interactive_parameters: true
  merge_api_options: false
  options:
    capabilities:
      CAPABILITY_IAM
    notification_topics:
    on_failure: nothing
    tags:
      creator: jd
  parameter_validation: default
  plan: true
  plan_only: false
  poll: true
  processing: true
```

**Comment by Johannes1509** [comment]
The presented solution of the issue https://github.com/sparkleformation/sparkle_formation/issues/273 to use an other version of bogo (e. g. v0.2.14) resolved my issue
