### ISSUE TITLE
SparkleFormation throws a rather unfriendly error when there are no resources in a template

### ISSUE THREAD

**Issue by cwjohnston** [sparkleformation/sparkle_formation#51]
Recently I was helping some new users get started with SparkleFormation, and we encountered this error when trying to render a template without any resources defined:

```
ERROR: NoMethodError: undefined method `detect' for nil:NilClass
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sparkle_formation-0.2.12/lib/sparkle_formation/sparkle_formation.rb:448:in `nested?'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sfn-0.3.8/lib/sfn/command_module/template.rb:33:in `load_template_file'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sfn-0.3.8/lib/sfn/command/create.rb:24:in `execute!'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sfn-0.3.8/bin/sfn:37:in `block (4 levels) in <top (required)>'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/bogo-cli-0.1.20/lib/bogo-cli/setup.rb:10:in `call'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/bogo-cli-0.1.20/lib/bogo-cli/setup.rb:10:in `block in bogo_cli_run'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/bogo-cli-0.1.20/lib/bogo-cli/setup.rb:27:in `define'
/Users/dthornton/.rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sfn-0.3.8/bin/sfn:6:in `<top (required)>'
/Users/dthornton/.rbenv/versions/2.1.4/bin/sfn:23:in `load'
/Users/dthornton/.rbenv/versions/2.1.4/bin/sfn:23:in `<main>'</pre>
```

I think it would be helpful for new users if we were to print a more informative message when we are unable to iterate on required hashes (e.g. Resources, Parameters, etc).

**Comment by chrisroberts** [comment]
This should be using a `#fetch` with a default value to prevent this exception from getting raised.

**Comment by chrisroberts** [comment]
Fixed in latest `develop` and will available on next release
