### ISSUE TITLE
Example does not work load_dynamics!': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by runningman84** [sparkleformation/sparkle_formation#57]
Based on your tutorial I have tried to create a dynamic config. 

```
user@user-VirtualBox:~/chefrepo/cloud/sparkle$ find cloudformation/
cloudformation/
cloudformation/components
cloudformation/components/region.rb
cloudformation/dynamics
cloudformation/dynamics/node.rb
user@user-VirtualBox:~/chefrepo/cloud/sparkle$ cat ec2_example.rb
SparkleFormation.new('ec2_example').load(:region).overrides do

  description "AWS CloudFormation Sample Template ..."

  %w(node1 node2 node3).each do |_node_name|
    dynamic!(:node, _node_name)
  end

  # and include one with predefined keypair

  dynamic!(:node, 'snowflake', :key_pair => 'snowkeys')
end

user@user-VirtualBox:~/chefrepo/cloud/sparkle$ cat d1.rb
require 'sparkle_formation'
require 'json'

puts JSON.pretty_generate(
  SparkleFormation.compile('ec2_sample.rb')
)
````

```
user@user-VirtualBox:~/chefrepo/cloud/sparkle$ ruby d1.rb 
/home/user/chefrepo/cloud/sparkle/cloudformation/dynamics/node.rb:10:in `block (2 levels) in load_dynamics!': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-0.3.0/lib/sparkle_formation/sparkle_formation.rb:206:in `instance_exec'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-0.3.0/lib/sparkle_formation/sparkle_formation.rb:206:in `insert'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-0.3.0/lib/sparkle_formation/sparkle_attribute.rb:313:in `dynamic!'
	from ec2_sample.rb:6:in `block (2 levels) in compile'
	from ec2_sample.rb:5:in `each'
	from ec2_sample.rb:5:in `block in compile'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-0.3.0/lib/sparkle_formation/sparkle_formation.rb:125:in `instance_exec'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-0.3.0/lib/sparkle_formation/sparkle_formation.rb:125:in `build'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-0.3.0/lib/sparkle_formation/sparkle_formation.rb:431:in `block in compile'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-0.3.0/lib/sparkle_formation/sparkle_formation.rb:427:in `each'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-0.3.0/lib/sparkle_formation/sparkle_formation.rb:427:in `compile'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-0.3.0/lib/sparkle_formation/sparkle_formation.rb:114:in `compile'
	from d1.rb:5:in `<main>'

```

**Comment by chrisroberts** [comment]
What's the contents of your `dynamics/node.rb` file?

**Comment by runningman84** [comment]
it is the same as your example:
```
SparkleFormation.dynamic(:node,
  :parameters => {
    :key_name => {
      :type => 'String',
      :description => 'Optionally make keypair static'
    }
  }
) do |_name, _config|

  if(_config[:key_name])
    parameters.set!("#{_name}_key_name".to_sym) do
      description 'Name of EC2 key pair'
      type 'String'
    end
  end

  dynamic!(:ec2_instance, _name) do
    properties do
      key_name _config.fetch(:key_name, ref!("#{_name}_key_name".to_sym))
      image_id map!(:region_map, 'AWS::Region', :ami)
      user_data baes64!('80')
    end
  end

  outputs("#{_name}_instance_id".to_sym) do
    description 'InstanceId of the newly created EC2 instance'
    value ref!("#{_name}_ec2_instance".to_sym)
  end
  outputs("#{_name}_az".to_sym) do
    description 'Availability Zone of the newly created EC2 instance'
    value attr!("#{_name}_ec2_instance".to_sym, :availability_zone)
  end
  outputs("#{_name}_public_ip".to_sym) do
    description 'Public IP address of the newly created EC2 instance'
    value attr!("#{_name}_ec2_instance".to_sym, :public_ip)
  end
  outputs("#{_name}_private_ip".to_sym) do
    description 'Private IP address of the newly created EC2 instance'
    value attr!("#{_name}_ec2_instance".to_sym, :private_ip)
  end
  outputs("#{_name}_public_dns".to_sym) do
    description 'Public DNSName of the newly created EC2 instance'
    value attr!("#{_name}_ec2_instance".to_sym, :public_dns_name)
  end
  outputs("#{_name}_private_dns".to_sym) do
    description 'Private DNSName of the newly created EC2 instance'
    value attr!("#{_name}_ec2_instance".to_sym, :private_dns_name)
  end
end
```

**Comment by chrisroberts** [comment]
This looks like an issue with the location of the template to compile. SparkleFormation is likely looking for the building block items within the working directory, and not the `cloudformation` directory. Try moving your template into the `cloudformation` directory, and then running it again.

**Comment by chrisroberts** [comment]
Closing this up due to lack of activity. If this is still a problem, please feel free to open a new issue. Thanks!
