### ISSUE TITLE
components from 0.3 do not work anymore

### ISSUE THREAD

**Issue by runningman84** [sparkleformation/sparkle_formation#62]
my base component looks like this:
```
require 'net/http'
require 'json'

amis = {}
amis['ubuntu'] = {}

response = Net::HTTP.get_response('cloud-images.ubuntu.com', '/locator/ec2/releasesTable')
ubuntu_version = '14.04 LTS'
ubuntu_arch = 'amd64'
ubuntu_date = nil

response.body.split("\n").each do |line|
  next if line.length < 15
  str_match = /\[.*\]/.match(line)
  data = JSON.parse(str_match.to_s)

  next unless data[2] == ubuntu_version
  next unless data[3] == ubuntu_arch
  # next unless data[4] == type

  region = data[0]
  type = data[4]
  ubuntu_date = data[5]

   #puts data.inspect

  str_match = /(ami-[0-9a-z]+)/.match(data[6])
  image = str_match.to_s
  amis['ubuntu'][region] = {} if amis['ubuntu'][region].nil?
  amis['ubuntu'][region][type] = image
end

SparkleFormation.build do
  type_io = 'hvm:ebs-io1'
  type_ssd = 'hvm:ebs-ssd'
  type_instance = 'hvm:instance-store'

  mappings.region_map do

    set!('us-east-1'._no_hump,
         s3_endpoint: 's3.amazonaws.com',
         ami_ubuntu_io: amis['ubuntu']['us-east-1'][type_io],
         ami_ubuntu_ssd: amis['ubuntu']['us-east-1'][type_ssd],
         ami_ubuntu_instance: amis['ubuntu']['us-east-1'][type_instance])
    set!('us-west-1'._no_hump,
         s3_endpoint: 's3-us-west-1.amazonaws.com',
         ami_ubuntu_io: amis['ubuntu']['us-west-1'][type_io],
         ami_ubuntu_ssd: amis['ubuntu']['us-west-1'][type_ssd],
         ami_ubuntu_instance: amis['ubuntu']['us-west-1'][type_instance])
    set!('us-west-2'._no_hump,
         s3_endpoint: 's3-us-west-2.amazonaws.com',
         ami_ubuntu_io: amis['ubuntu']['us-west-2'][type_io],
         ami_ubuntu_ssd: amis['ubuntu']['us-west-2'][type_ssd],
         ami_ubuntu_instance: amis['ubuntu']['us-west-2'][type_instance])
    set!('eu-west-1'._no_hump,
         s3_endpoint: 's3-eu-west-1.amazonaws.com',
         ami_ubuntu_io: amis['ubuntu']['eu-west-1'][type_io],
         ami_ubuntu_ssd: amis['ubuntu']['eu-west-1'][type_ssd],
         ami_ubuntu_instance: amis['ubuntu']['eu-west-1'][type_instance])
    set!('eu-central-1'._no_hump,
         s3_endpoint: 's3-eu-central-1.amazonaws.com',
         ami_ubuntu_io: amis['ubuntu']['eu-central-1'][type_io],
         ami_ubuntu_ssd: amis['ubuntu']['eu-central-1'][type_ssd],
         ami_ubuntu_instance: amis['ubuntu']['eu-central-1'][type_instance])
    set!('sa-east-1'._no_hump,
         s3_endpoint: 's3-sa-east-1.amazonaws.com',
         ami_ubuntu_io: amis['ubuntu']['sa-east-1'][type_io],
         ami_ubuntu_ssd: amis['ubuntu']['sa-east-1'][type_ssd],
         ami_ubuntu_instance: amis['ubuntu']['sa-east-1'][type_instance])
    set!('ap-southeast-1'._no_hump,
         s3_endpoint: 's3-ap-southeast-1.amazonaws.com',
         ami_ubuntu_io: amis['ubuntu']['ap-southeast-1'][type_io],
         ami_ubuntu_ssd: amis['ubuntu']['ap-southeast-1'][type_ssd],
         ami_ubuntu_instance: amis['ubuntu']['ap-southeast-1'][type_instance])
    set!('ap-northeast-1'._no_hump,
         s3_endpoint: 's3-ap-northeast-1.amazonaws.com',
         ami_ubuntu_io: amis['ubuntu']['ap-northeast-1'][type_io],
         ami_ubuntu_ssd: amis['ubuntu']['ap-northeast-1'][type_ssd],
         ami_ubuntu_instance: amis['ubuntu']['ap-northeast-1'][type_instance])
  end

  outputs.creator do
    description 'Stack creator'
    value ENV['USER']
  end

  outputs.ubuntu_ami_age do
    description 'Ubuntu AMI date'
    value ubuntu_date
  end

  outputs.ubuntu_ami_version do
    description 'Ubuntu AMI version'
    value ubuntu_version
  end

  outputs.ubuntu_ami_arch do
    description 'Ubuntu AMI arch'
    value ubuntu_arch
  end


end

```

This is not working anymore in 1.0:
```
/home/user/chefrepo/cloud/sparkle/cloudformation/components/base.rb:7:in `block (2 levels) in load_parts!': uninitialized constant #<Class:0x000000018e4440>::Net (NameError)
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-1.0.0/lib/sparkle_formation/sparkle.rb:325:in `instance_eval'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-1.0.0/lib/sparkle_formation/sparkle.rb:325:in `block (2 levels) in load_parts!'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-1.0.0/lib/sparkle_formation/sparkle.rb:324:in `each'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-1.0.0/lib/sparkle_formation/sparkle.rb:324:in `block in load_parts!'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/bogo-0.1.28/lib/bogo/memoization.rb:60:in `memoize'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-1.0.0/lib/sparkle_formation/sparkle.rb:323:in `load_parts!'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-1.0.0/lib/sparkle_formation/sparkle.rb:216:in `initialize'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-1.0.0/lib/sparkle_formation/sparkle_formation.rb:318:in `new'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-1.0.0/lib/sparkle_formation/sparkle_formation.rb:318:in `initialize'
	from templates/base.rb:1:in `new'
	from templates/base.rb:1:in `compile'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-1.0.0/lib/sparkle_formation/sparkle_formation.rb:97:in `instance_eval'
	from /home/user/.chefdk/gem/ruby/2.1.0/gems/sparkle_formation-1.0.0/lib/sparkle_formation/sparkle_formation.rb:97:in `compile'
	from asy.rb:10:in `block in <main>'
	from asy.rb:6:in `each'
	from asy.rb:6:in `<main>
```

**Comment by runningman84** [comment]
changing
response = Net::HTTP.get_response('cloud-images.ubuntu.com', '/locator/ec2/releasesTable')
to
response = ::Net::HTTP.get_response('cloud-images.ubuntu.com', '/locator/ec2/releasesTable')
sovled the problem
